#docker-compose.yml
services:
  db:
    image: postgres:15
    container_name: wandinha_postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: wandinha_redis_cache
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NOSSO BOT (fastapi)
  wandinha_bot:
    container_name: wandinha-bot
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - evolution_api
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --proxy-headers

  evolution_api:
    image: atendai/evolution-api:v1.8.0
    container_name: wandinha_evolution_api
    restart: always
    env_file:
      - .env
    environment:
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=http://wandinha-bot:8000/webhook
      - WEBHOOK_GLOBAL_EVENTS=MESSAGES_UPSERT
      - DATABASE_CONNECTION_URI=${POSTGRES_CONNECTION_URI}
      - CACHE_ENABLED=true
      - CACHE_PROVIDER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  evolution_store:
  evolution_instances: